version: "2.1"
services:
   intellij-sve-postgres:
        container_name: intellij-sve-postgres
        image: postgres:latest
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=password
            - POSTGRES_ROOT_PASSWORD=password
            - POSTGRES_DATABASE=postgres
        mem_limit: 512m
        cpu_shares: 2
   intellij-sve-wildfly:
        container_name: intellij-sve-wildfly
        image: intellij-sve-wildfly
        build:
            context: ./Wildfly
            args:
               - WILDFLY_ADMIN_USER=admin
               - WILDFLY_ADMIN_PASSWORD=admin123!
               - WILDFLY_USER=jboss
               - WILDFLY_PASSWORD=fhbay-mdb1
        mem_limit: 512m
        cpu_shares: 4
        depends_on:
            - intellij-sve-postgres
        ports:
            - "8080:8080"
            - "9990:9990"
            - "8787:8787"
        volumes:
            - ./deployments:/opt/jboss/wildfly/standalone/deployments:rw
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=password
            - POSTGRES_DATABASE=postgres
            - POSTGRES_PORT_5432_TCP_ADDR=intellij-sve-postgres
            - POSTGRES_PORT_5432_TCP_PORT=5432
